# Generated by Django 5.0.6 on 2024-07-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_producto_remove_factura_productos_factura_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descripción no proporcionada'),
        ),
    ]
