# Generated by Django 5.0.6 on 2024-07-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_producto_remove_factura_productos_factura_total_and_more'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
